### ISSUE TITLE
`unified` not an available package

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-content#314]
I ran:
```
cd /tmp
git clone https://github.com/mdn/stumptown-content.git
cd stumptown-content
npm install
npm run build-json
```

And I get:

```
▶ npm run build-json

> stump@0.1.0 build-json /private/tmp/stumptown-content
> node scripts/build-json/build-json.js

internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module 'unified'
Require stack:
- /private/tmp/stumptown-content/scripts/build-json/markdown-converter.js
- /private/tmp/stumptown-content/scripts/build-json/resolve-contributors.js
- /private/tmp/stumptown-content/scripts/build-json/build-page-json.js
- /private/tmp/stumptown-content/scripts/build-json/build-json.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/private/tmp/stumptown-content/scripts/build-json/markdown-converter.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/tmp/stumptown-content/scripts/build-json/markdown-converter.js',
    '/private/tmp/stumptown-content/scripts/build-json/resolve-contributors.js',
    '/private/tmp/stumptown-content/scripts/build-json/build-page-json.js',
    '/private/tmp/stumptown-content/scripts/build-json/build-json.js'
  ]
}
```

the package is required [here for example](https://github.com/mdn/stumptown-content/blob/22081538d0061e98c8c184994d0fd411bbd68124/scripts/build-json/markdown-converter.js#L1) but there is no `unified` in [`package.json`](https://github.com/mdn/stumptown-content/blob/22081538d0061e98c8c184994d0fd411bbd68124/package.json).

**Comment by ddbeck** [comment]
Thanks for noting this, @peterbe. I opened #315 to fix it.
